import type { Metadata } from "next";
import { Roboto, Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "GadyetHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={` ${roboto.variable} dark antialiased `}>
        {/* <SidebarProvider className="lg:hidden ">
          <AppSidebar /> */}
        <main>
          {/* <SidebarTrigger /> */}
          {children}
        </main>
        <Toaster position="top-right" />
        {/* </SidebarProvider> */}
      </body>
    </html>
  );
}
